### PR TITLE
Windows Forms Integration Example fixes

### PR DESCRIPTION
**Pull request by pavlalexandr**
1. Removed indian style code 
Program.container = container 
from the end of Bootstrap method. 
2. Method Application.SetCompatibleTextRenderingDefault(false); will throw an exception if Bootstrap() will be called before it. So I replaced Bootstrap after SetCompatibleTextRenderingDefault.

### CODE REVIEW

**Comment by dotnetjunkie** [comment]
Thanks for your pull request. I'm not familiar with the term 'indian style code'. Can you explain?

**Comment by pavlalexandr** [comment]
Sorry for my humor. I mean that this expression doesn't make any sense in the method.

**Comment by dotnetjunkie** [comment]
I'm not sure that the native Americans will appreciate that you think they don't make sens :-) But eitherway, thanks for your pull request. I do appreciate it.

**Comment by pavlalexandr** [comment]
Actually I mean Indians who lives in India :). But you are right anyway, they won't appreciate that neither.
I am glad that my contribution was helpful.

**Pull request merged**
