### PR TITLE
Wpf documentation update

### PR DESCRIPTION
**Pull request by beannaich**
The previous documentation made assumptions about WPF that were unsubstantiated and untrue. WPF absolutely allows for constructor injection with only minor changes to App.xaml.

### CODE REVIEW

**Comment by dotnetjunkie** [comment]
Thank you for submitting this. We will review and test your change. This might take some time though.

**Comment by beannaich** [comment]
I expect nothing less. :smile:

**Comment by beannaich** [comment]
@dotnetjunkie Are you guys aware of the `x:FactoryMethod` and `x:Argument` XAML elements? It seems like these could be utilized to build a bridge between Simple Injector and WPF, allowing controls to be injected as well.

If you'd like I can investigate this and if it's worth doing, begin developing a WPF extension project.

**Comment by qujck** [comment]
That sounds great. Take a look [here](https://simpleinjector.readthedocs.org/en/latest/contribute.html) and start a discussion [here](https://simpleinjector.codeplex.com/discussions)

**Comment by dotnetjunkie** [comment]
Hi Beannaich, thanks for your pull request. I decided to decline your pull request, and instead use the knowledge gained from your and TheBigRic's pull requests to create another version. So although I didn't accept your pull request, your contribution has proven to be very valuable. Thanks for contributing to Simple Injector.

**Comment by beannaich** [comment]
Not a problem, I am working on a DI framework similar to Prism, except with all containers in mind (not just Unity and MEF), and takes a minimalist approach.

Hopefully when that's done the documentation on this subject can be again improved.

Thanks for your unending commitment to Simple Injector and DI in general :smile:

**Pull request closed without merging**
