### PR TITLE
  simplification wpfintegration.rst

### PR DESCRIPTION
**Pull request by YehudahA**
Instead of creating new entry point and change the project startup, we can use the ready-for-use app.xaml.cs.

### CODE REVIEW

**Comment by qujck** [comment]
Hi @YehudahA,

thanks for taking the time to submit this pull request, I can see where you are going with the simplification but there are a few problems with your PR as it stands. E.g. spelling mistakes (_Cahange the App.xaml.cs_) and inconsistent variable names (`private readonly IUserRepository userContext;`)

The other thing to bear in mind is that our current example promotes some of our standard abstractions: [commands](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=91) and [queries](https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=92)

```csharp
public IEnumerable<User> Users {
    get { return this.queryProcessor.Execute(new GetAllUsers()); }
}
```

**Comment by YehudahA** [comment]
OK, I will fix it. Meanwhile, I read all your blog..

**Comment by YehudahA** [comment]
I doubt if injection the ViewModel with the constructor is the best practice.
I need to check whether parameterized constructor may make problems with the designer.

**Comment by YehudahA** [comment]
I did.

**Comment by YehudahA** [comment]
^^^

**Comment by dotnetjunkie** [comment]
Sorry for the huge delay. I decided to leave this guidance the way it is, and will not merge this PR.

**Pull request closed without merging**
