### PR TITLE
harder InterceptorProxy.InvokeMethodCall

### PR DESCRIPTION
**Pull request by BLun78**
Add try/catch in Proceeding.
So the proxy throw an exception at the called method code and not in the interception code.
So it is a perfekt :)

### CODE REVIEW

**Comment by qujck** [comment]
Hi @BLun78,

Thanks for the PR. I'm not sure that swallowing exceptions is the best option. Could you give an example of a use case where you would require the code to work this way?

**Comment by BLun78** [comment]
Test yours an my code with a consoleapplication.

```C#
namespace ConsoleApplication1
{
    using System;
    using System.Diagnostics;
    using System.Globalization;
    using ConsoleApplication1.Interception;
    using Serilog;
    using SimpleInjector;

    public interface IBoo
    {
        bool DoSomething();
    }

    public class Boo : IBoo

    {
        public bool DoSomething()
        {
            Console.WriteLine("DoSomething");
            throw new NotImplementedException("DoSomething make Exeption!"); 
        }
    }

    internal class MonitoringInterceptor : IInterceptor
    {
        private readonly ILogger logger;

        public MonitoringInterceptor(ILogger logger)
        {
            this.logger = logger;
        }

        public void Intercept(IInvocation invocation)
        {
            var decoratedType = invocation.InvocationTarget.GetType();
            var watch = Stopwatch.StartNew();

            this.logger.Information(
                string.Format(CultureInfo.InvariantCulture, "Start: {0} executed", decoratedType.Name));

            invocation.Proceed();
            
            this.logger.Information(
                string.Format(
                    CultureInfo.InvariantCulture,
                    "End  : {0} executed in {1} ms.",
                    decoratedType.Name,
                    watch.ElapsedMilliseconds));
        }

        public class Program
        {
            static void Main(string[] args)
            {
                container = new Container();
                container.Register<ILogger>(
                    () => new LoggerConfiguration().WriteTo.File(@"Serilog.log").CreateLogger());

                container.Register<IBoo, Boo>();
                container.InterceptWith<MonitoringInterceptor>(type => type == typeof(IBoo));

                container.Verify();

                DoSomething();
            }

            private static Container container;

            public static void DoSomething()
            {
                var boo = container.GetInstance<IBoo>();


                boo.DoSomething(); 

            }
        }
    }
}
```

Your code throw the exception here:
```C#
private sealed class InterceptorProxy : RealProxy
{
    //..... code .....

    private IMessage InvokeMethodCall(IMethodCallMessage message)
    {
        var invocation =
            new Invocation { Proxy = this, Message = message, Arguments = message.Args };

        invocation.Proceeding += () => {

            // Exception throws here
            // ====>>>>>>>>>>>>  throw Exception in the stactrace => message.MethodBase.Invoke(this.realInstance, invocation.Arguments);
            invocation.ReturnValue = message.MethodBase.Invoke(this.realInstance, invocation.Arguments);
        };

        this.interceptor.Intercept(invocation);
        return new ReturnMessage(invocation.ReturnValue, invocation.Arguments,
            invocation.Arguments.Length, null, message);
    }
    
    //..... code .....
}
```

With the change you get the stacktrace here:
```C#
public class Program
{
    //..... code .....

    private static Container container;

    public static void DoSomething()
    {
        var boo = container.GetInstance<IBoo>();

        // Exceptio throws here
        // ====>>>>>>>>>>>>  throw exception in the stactrace  => boo.DoSomething()
        boo.DoSomething();
    }
}
```
So the exception proxy works. I hope it helps.

**Comment by dotnetjunkie** [comment]
Hi @BLun78,

Thanks for taking the time to create this pull request. We appreciate it.

Unfortunately, I'm afraid that your adjustment causes behavior that most developers won't expect. Interceptors are expected to behave similarly to how decorators -and normal code- would behave, when it comes to exception handling. This means that thrown exceptions should bubble up the call stack and code will only start running again when a `catch` or `finally` statement is found.

With your change however, you prevent the exception to bubble up directly, which causes the code in interceptors to keep running, while we would normally expect the exception to cause this method to be jumped out when an intercepted object throws an exception. Not doing this could cause bugs, because:
 1. Developers are not used to this behavior
 2. It makes it really hard to detect whether the interceptee has thrown an exception. Many interceptors need to handle exceptions, for instance by logging them, and your change makes it really hard to do so.

Instead, if we want the code in the interceptor to keep running, we should wrap the code in a try-finally, as follows:

``` c#
public void Intercept(IInvocation invocation)
{
    var decoratedType = invocation.InvocationTarget.GetType();
    var watch = Stopwatch.StartNew();

    this.logger.Information(
        string.Format(CultureInfo.InvariantCulture, "Start: {0} executed", decoratedType.Name));

    try
    {
        invocation.Proceed();
    }
    finally
    {
        this.logger.Information(
            string.Format(
                CultureInfo.InvariantCulture,
                "End  : {0} executed in {1} ms.",
                decoratedType.Name,
                watch.ElapsedMilliseconds));
    }
}
```

Since you model makes it really hard to catch exceptions inside interceptors, and since most developers would expect this behavior; I decided not to accept this pull request.

I hope you can understand my reasoning and my decision.

**Comment by BLun78** [comment]
Hallo Steven,

thx for that you explain your opinion. Sorry for my bad english but i want to try it out.
I would try show you my opion. I mean a interception must work and doesn't break by a exception of the delegation. Your try/finally hide the exception.

I start a new better try for a changerequest:

```C#
public interface IInvocation
    {
        Exception Exception { get; set; }  //new Information on the interface
        object InvocationTarget { get; }
        object ReturnValue { get; set; }
        object[] Arguments { get; }
        void Proceed();
        MethodBase GetConcreteMethod();
    }

private sealed class InterceptorProxy : RealProxy
{
    private static MethodBase GetTypeMethod = typeof(object).GetMethod("GetType");

    private object realInstance;
    private IInterceptor interceptor;

    [DebuggerStepThrough]
    public InterceptorProxy(Type classToProxy, object realInstance,
                            IInterceptor interceptor)
        : base(classToProxy)
    {
        this.realInstance = realInstance;
        this.interceptor = interceptor;
    }

    public override IMessage Invoke(IMessage msg)
    {
        if (msg is IMethodCallMessage)
        {
            var message = (IMethodCallMessage)msg;

            if (object.ReferenceEquals(message.MethodBase, GetTypeMethod))
            {
                return this.Bypass(message);
            }
            else {
                return this.InvokeMethodCall(message);
            }
        }

        return msg;
    }

    private IMessage InvokeMethodCall(IMethodCallMessage message)
    {
        var invocation = new Invocation
        {
            Proxy = this,
            Message = message,
            Arguments = message.Args,
            Exception = default(Exception)
        };

        invocation.Proceeding += () =>
        {
            try
            {
                invocation.ReturnValue = message.MethodBase.Invoke(this.realInstance, invocation.Arguments);
            }
            catch (Exception ex)
            {
                invocation.Exception = ex;
            }
        };

        this.interceptor.Intercept(invocation);

        if (invocation.Exception == default(Exception))
        {
            return new ReturnMessage(invocation.ReturnValue, invocation.Arguments,
                invocation.Arguments.Length, null, message);
        }
        else
        {
            return new ReturnMessage(invocation.Exception, message);
        }
    }

    private IMessage Bypass(IMethodCallMessage message)
    {
        object value = message.MethodBase.Invoke(this.realInstance, message.Args);

        return new ReturnMessage(value, message.Args, message.Args.Length, null, message);
    }

    private class Invocation : IInvocation
    {
        public event Action Proceeding;
        public InterceptorProxy Proxy { get; set; }
        public object[] Arguments { get; set; }
        public IMethodCallMessage Message { get; set; }
        public object ReturnValue { get; set; }
        public Exception Exception { get; set; }

        public object InvocationTarget
        {
            get { return this.Proxy.realInstance; }
        }

        public void Proceed()
        {
            this.Proceeding();
        }

        public MethodBase GetConcreteMethod()
        {
            return this.Message.MethodBase;
        }
    }
}
```

My Implementation of the Interception is:
```C#
internal class MonitoringInterceptor : IInterceptor
    {
        private readonly ILogger logger;

        public MonitoringInterceptor(ILogger logger)
        {
            this.logger = logger;
        }

        public void Intercept(IInvocation invocation)
        {
            var decoratedType = invocation.InvocationTarget.GetType();
            var watch = Stopwatch.StartNew();

            this.logger.Information(string.Format(CultureInfo.InvariantCulture,
                "Start: {0} executed",
                decoratedType.Name));

            // Calls the decorated instance.
            invocation.Proceed();

            if (invocation.Exception != default(Exception))
            {
                // do some thing with exception
                this.logger.Information(string.Format(CultureInfo.InvariantCulture,
                  "End  : {0} executed in {1} ms. Exception: {2}",
                  decoratedType.Name, watch.ElapsedMilliseconds, invocation.Exception.Source));
            }
            else
            {
                // do somethink without exception
                this.logger.Information(string.Format(CultureInfo.InvariantCulture,
               "End  : {0} executed in {1} ms.",
               decoratedType.Name, watch.ElapsedMilliseconds));
            }
        }
    }
```
Your Points:

**Comment by dotnetjunkie** [comment]
> Your try/finally hide the exception.

A `finally` block will not stop a thrown exception; the exception will continue to bubble up the call stack. You can’t stop an exception from bubbling in a `finally`. You can of course in a `catch` block, but this should be common knowledge to .NET developers.

>  i didn't want to write in every IInterceptor implementation the try/catch

You only need a catch statement if you actually want to handle that exception.

As I explained, the code you provided is not suited as general approach for all developers and is for that reason I don't want to integrate it in our documentation. If this is the behavior you want for your application, you are of course free to adjust the example code in your application, that's why it is provided as code snippets on the web site. Also note that if you switch to Castle.DynamicProxy as interception framework, you will get the same behavior as the documentation provides.

Thanks for your understanding.


Steven

**Pull request closed without merging**
