### PR TITLE
mvcintegration: Add required attribute

### PR DESCRIPTION
**Pull request by fbontin**

### CODE REVIEW

**Comment by dotnetjunkie** [comment]
Hi @fbontin,

In the integrating example, the `Application_Start` contains the whole configuration required to get Simple Injector running. On top of that, one might have other start-ups code such as the code your attribute refers to, but that's optional -and as I see it- irrelevant to the given integration guide.

Can you explain why you think this attribute should be added?

**Comment by fbontin** [comment]
Hi @dotnetjunkie! 

Thanks for the quick answer. The reason I included it was that my project would not work without that line. I am by no means a SimpleInjector expert so it is probably an error on my side, but I got the idea that it was needed to make it work.

**Comment by dotnetjunkie** [comment]
Whether or not you need this attribute depends on several factors, so I don't think it's good to include it here in the docs.

**Comment by fbontin** [comment]
Yeah, okay, that makes sense. Might be worth mentioning somewhere maybe?

**Comment by dotnetjunkie** [comment]
> Might be worth mentioning somewhere maybe?

Good point. I'll take a look at where and how this could be documented.

**Pull request closed without merging**
