### PR TITLE
Update InterceptionExtensions.rst

### PR DESCRIPTION
**Pull request by koljada**
Correct typos.

### CODE REVIEW

**Comment by dotnetjunkie** [comment]
Thanks.

**Comment by koljada** [comment]
You're welcome! It would be great to have a nuget package with all this Interception stuff

**Comment by dotnetjunkie** [comment]
> It would be great to have a nuget package with all this Interception stuff

The reasoning behind the lack of interception support is explained in the [design decisions section](https://simpleinjector.readthedocs.io/en/latest/decisions.html#no-interception) of the documentation.

**Comment by koljada** [comment]
Thanks a lot! I will try to use decorators instead

**Pull request merged**
